settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel

- name: centos-7
  driver:
    image: centos:7

suites:
- name: default
  run_list:
  - recipe[yum-ius::default]
  attributes: {}
